version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
        environment:
          ## this enables colors in the output
          TERM: xterm

    working_directory: ~/react-markdown-editor

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: yarn test

      - run:
          name: Run ESLint
          command: yarn lint

      - run:
          name: Run Flow
          command: yarn flow:check

#      Not yet :/
#      - run:
#          name: Run Cypress
#          command: yarn cypress
#
